name: New students Api Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Generate build
    runs-on: ubuntu-latest
    env:
      NODE_ENV: ${{secrets.NODE_ENV}}
      PORT: ${{secrets.PORT}}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - name: Create Build
        run: npm run build

      - name: Show build dist
        run: ls dist
