name: New students Api Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Generate build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm run test

      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "ger-config"
          heroku_email: ${{secrets.HEROKU_USER_EMAIL}}
          stack: "container"
          healthcheck: "https://ger-config.herokuapp.com/ping"
          checkstring: "pong v2"
          delay: 5
          rollbackonhealthcheckfailed: true
